spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}

app:
  cors:
    allowed-origins:
      - ${CLIENT_URL}
  auth:
    token-secret: ${TOKEN_SECRET}
    token-expiration: ${TOKEN_EXPIRATION}
  oauth2:
    redirect-uri: ${CLIENT_URL}/oauth2/redirect
